[2025-06-27T06:22:46.807+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-27T06:22:46.840+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ga4_raw_data_elt_v1.0_dev.end_task scheduled__2025-02-14T02:10:00+00:00 [queued]>
[2025-06-27T06:22:46.848+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ga4_raw_data_elt_v1.0_dev.end_task scheduled__2025-02-14T02:10:00+00:00 [queued]>
[2025-06-27T06:22:46.850+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-06-27T06:22:46.876+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): end_task> on 2025-02-14 02:10:00+00:00
[2025-06-27T06:22:46.915+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=990) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-27T06:22:46.921+0000] {standard_task_runner.py:72} INFO - Started process 1005 to run task
[2025-06-27T06:22:46.934+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ga4_raw_data_elt_v1.0_dev', 'end_task', 'scheduled__2025-02-14T02:10:00+00:00', '--job-id', '238', '--raw', '--subdir', 'DAGS_FOLDER/GA4_data_elt.py', '--cfg-path', '/tmp/tmpspdwac3l']
[2025-06-27T06:22:46.952+0000] {standard_task_runner.py:105} INFO - Job 238: Subtask end_task
[2025-06-27T06:22:47.105+0000] {task_command.py:467} INFO - Running <TaskInstance: ga4_raw_data_elt_v1.0_dev.end_task scheduled__2025-02-14T02:10:00+00:00 [running]> on host 4e2c61145aac
[2025-06-27T06:22:47.228+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ga4_raw_data_elt_v1.0_dev' AIRFLOW_CTX_TASK_ID='end_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T02:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T02:10:00+00:00'
[2025-06-27T06:22:47.232+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-27T06:22:47.242+0000] {logging_mixin.py:190} INFO - end
[2025-06-27T06:22:47.245+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-06-27T06:22:47.260+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-27T06:22:47.261+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ga4_raw_data_elt_v1.0_dev, task_id=end_task, run_id=scheduled__2025-02-14T02:10:00+00:00, execution_date=20250214T021000, start_date=20250627T062246, end_date=20250627T062247
[2025-06-27T06:22:47.304+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-27T06:22:47.331+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-27T06:22:47.333+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
