[2025-06-27T06:18:42.108+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-27T06:18:42.135+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ga4_raw_data_elt_v1.0_dev.create_ga4_events_dataset scheduled__2025-01-07T02:10:00+00:00 [queued]>
[2025-06-27T06:18:42.162+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ga4_raw_data_elt_v1.0_dev.create_ga4_events_dataset scheduled__2025-01-07T02:10:00+00:00 [queued]>
[2025-06-27T06:18:42.164+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-06-27T06:18:42.188+0000] {taskinstance.py:2888} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_ga4_events_dataset> on 2025-01-07 02:10:00+00:00
[2025-06-27T06:18:42.206+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4339) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-27T06:18:42.213+0000] {standard_task_runner.py:72} INFO - Started process 4364 to run task
[2025-06-27T06:18:42.215+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ga4_raw_data_elt_v1.0_dev', 'create_ga4_events_dataset', 'scheduled__2025-01-07T02:10:00+00:00', '--job-id', '1078', '--raw', '--subdir', 'DAGS_FOLDER/GA4_data_elt.py', '--cfg-path', '/tmp/tmpnh_1rcga']
[2025-06-27T06:18:42.251+0000] {standard_task_runner.py:105} INFO - Job 1078: Subtask create_ga4_events_dataset
[2025-06-27T06:18:42.455+0000] {task_command.py:467} INFO - Running <TaskInstance: ga4_raw_data_elt_v1.0_dev.create_ga4_events_dataset scheduled__2025-01-07T02:10:00+00:00 [running]> on host 546ad4141aeb
[2025-06-27T06:18:42.653+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ga4_raw_data_elt_v1.0_dev' AIRFLOW_CTX_TASK_ID='create_ga4_events_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T02:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-07T02:10:00+00:00'
[2025-06-27T06:18:42.660+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-27T06:18:42.680+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-06-27T06:18:42.687+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-06-27T06:18:42.690+0000] {bigquery.py:533} INFO - datasetId was not specified in `dataset_reference`. Will use default value ga4_events_dev.
[2025-06-27T06:18:42.692+0000] {bigquery.py:533} INFO - projectId was not specified in `dataset_reference`. Will use default value sixth-topic-349709.
[2025-06-27T06:18:42.694+0000] {bigquery.py:544} INFO - Creating dataset: ga4_events_dev in project: sixth-topic-349709 
[2025-06-27T06:18:44.103+0000] {bigquery.py:548} INFO - Dataset created successfully.
[2025-06-27T06:18:44.182+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-27T06:18:44.183+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ga4_raw_data_elt_v1.0_dev, task_id=create_ga4_events_dataset, run_id=scheduled__2025-01-07T02:10:00+00:00, execution_date=20250107T021000, start_date=20250627T061842, end_date=20250627T061844
[2025-06-27T06:18:44.235+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-27T06:18:44.294+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-27T06:18:44.295+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-06-27T06:20:26.210+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-27T06:20:26.277+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ga4_raw_data_elt_v1.0_dev.create_ga4_events_dataset scheduled__2025-01-07T02:10:00+00:00 [queued]>
[2025-06-27T06:20:26.296+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ga4_raw_data_elt_v1.0_dev.create_ga4_events_dataset scheduled__2025-01-07T02:10:00+00:00 [queued]>
[2025-06-27T06:20:26.299+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-06-27T06:20:26.338+0000] {taskinstance.py:2888} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_ga4_events_dataset> on 2025-01-07 02:10:00+00:00
[2025-06-27T06:20:26.370+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=126) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-27T06:20:26.382+0000] {standard_task_runner.py:72} INFO - Started process 162 to run task
[2025-06-27T06:20:26.391+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ga4_raw_data_elt_v1.0_dev', 'create_ga4_events_dataset', 'scheduled__2025-01-07T02:10:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/GA4_data_elt.py', '--cfg-path', '/tmp/tmpv91nxqsa']
[2025-06-27T06:20:26.417+0000] {standard_task_runner.py:105} INFO - Job 27: Subtask create_ga4_events_dataset
[2025-06-27T06:20:26.582+0000] {task_command.py:467} INFO - Running <TaskInstance: ga4_raw_data_elt_v1.0_dev.create_ga4_events_dataset scheduled__2025-01-07T02:10:00+00:00 [running]> on host 4e2c61145aac
[2025-06-27T06:20:26.779+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ga4_raw_data_elt_v1.0_dev' AIRFLOW_CTX_TASK_ID='create_ga4_events_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T02:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-07T02:10:00+00:00'
[2025-06-27T06:20:26.783+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-27T06:20:26.797+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-06-27T06:20:26.805+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-06-27T06:20:26.807+0000] {bigquery.py:533} INFO - datasetId was not specified in `dataset_reference`. Will use default value ga4_events_dev.
[2025-06-27T06:20:26.808+0000] {bigquery.py:533} INFO - projectId was not specified in `dataset_reference`. Will use default value sixth-topic-349709.
[2025-06-27T06:20:26.814+0000] {bigquery.py:544} INFO - Creating dataset: ga4_events_dev in project: sixth-topic-349709 
[2025-06-27T06:20:28.103+0000] {bigquery.py:548} INFO - Dataset created successfully.
[2025-06-27T06:20:28.213+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-27T06:20:28.214+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ga4_raw_data_elt_v1.0_dev, task_id=create_ga4_events_dataset, run_id=scheduled__2025-01-07T02:10:00+00:00, execution_date=20250107T021000, start_date=20250627T062026, end_date=20250627T062028
[2025-06-27T06:20:28.287+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-27T06:20:28.339+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
